### ISSUE TITLE
Fix this ton of errors

### ISSUE THREAD

**Issue by thebigsmileXD** [thebigsmileXD/BetterGen#1]
![image](https://cloud.githubusercontent.com/assets/8733998/25940057/2c12a798-3635-11e7-93ed-23f4fdab9c22.png)

@Ad5001

lol vs
![image](https://cloud.githubusercontent.com/assets/8733998/25940052/2931716c-3635-11e7-8f31-5b3422f047e9.png)

**Comment by Ad5001** [comment]
It depends on your code style. Cause I dont get any error in my IDE. Can you develop these parties?

**Comment by thebigsmileXD** [comment]
I am on it. Most undefined are just stupid tesseract fixes. Simply drop the support ;)

**Comment by Ad5001** [comment]
I wont drop the support because some major software still uses it.

**Comment by thebigsmileXD** [comment]
I see. Then i'll keep it in, keep the code messy, but i'll fix those other issues. like: variables not being defined etc. Copy paste does not solve everything, dude.

**Comment by Ad5001** [comment]
Umm what? I did indeed copy some code (gaussian kernel and getHighestWorkableBlock ) but I didnt copy without adapting.
For undefined vars, it might be because I switch the t and the h pf height xD

**Comment by thebigsmileXD** [comment]
Nope. $zz = $z -> both undefined, whereever that 2 should come from

**Comment by thebigsmileXD** [comment]
Or look at this:
![image](https://cloud.githubusercontent.com/assets/8733998/25944627/45d28c3e-3644-11e7-9684-2a6922d0c861.png)
Where do you return the bool? ;)

**Comment by thebigsmileXD** [comment]
![image](https://cloud.githubusercontent.com/assets/8733998/25944718/9f5373d6-3644-11e7-9ee0-01ed1ae370e9.png)
Or this.

**Comment by Ad5001** [comment]
Ah this maybe thz case for the first one. But the second one works and returns a biome

**Comment by thebigsmileXD** [comment]
@Ad5001 it doesn't $ = variable, not function. You try to execute a function call, instead of getting the value of an array 
> []

**Comment by Ad5001** [comment]
Oh damn. havent seen that lol.

**Comment by thebigsmileXD** [comment]
I am fixing it all. Don't worry

**Comment by thebigsmileXD** [comment]
https://github.com/thebigsmileXD/BetterGen/blob/master/src/Ad5001/BetterGen/populator/MineshaftPopulator.php#L165
Lol..
