### ISSUE TITLE
When I spawn a world it crashes server

### ISSUE THREAD

**Issue by DerddyDert** [thebigsmileXD/BetterGen#2]
Error: Access level to Ad5001\BetterGen\structure\SakuraTree::$leafType must be public (as in class pocketmine\level\generator\object\Tree)
File: /BetterGen-master/src/Ad5001/BetterGen/structure/SakuraTree
Line: 0
Type: E_COMPILE_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN : BetterGen v1.1

**Comment by thebigsmileXD** [comment]
Actually its a E_COMPILE_ERROR. I've been running it from src
